export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';
export const CHANGE_TAB = 'CHANGE_TAB';

export const RECEIVE_SHIFTS_DATA = 'RECEIVE_SHIFTS_DATA';
export const REQUEST_SHIFTS = 'REQUEST_SHIFTS';
export const REQUEST_SCHEDULE = 'REQUEST_SCHEDULE';
export const RECEIVE_SCHEDULE = 'RECEIVE_SCHEDULE';
export const AWAITING_AUTH_RESPONSE = 'AWAITING_AUTH_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AFTER_ANIMATIONS = 'AFTER_ANIMATIONS';
export const EDIT_SHIFT = 'EDIT_SHIFT';
export const NEW_SHIFT = 'NEW_SHIFT';
export const SHIFT_EDIT_SUCCESS = 'SHIFT_EDIT_SUCCESS';
export const CLEAR_EDIT = 'CLEAR_EDIT';
export const SHIFT_EDIT_SENT = 'SHIFT_EDIT_SENT';

export const NEXT_MONTH = 'NEXT_MONTH';
